### ISSUE TITLE
4channel.py: command not found

### ISSUE THREAD

**Issue by FormerlyChucks** [fatalhalt/fourchannel#1]
After following the `README.md` file, `4channel.py` will give the following result:

    -bash: 4channel.py: command not found
    
After looking at the `setup.py` file, it is clear that `4channel` should be used instead. May you update the README? I can do so in a PR if needed.

**Comment by fatalhalt** [comment]
Updated. Good eyes, thanks.

**Comment by FormerlyChucks** [comment]
Glad to help! Thanks for making this tool. I'll be closing the issue now :)
